version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - data-storage:/data/storage
      - data-tmp:/data/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - servernet
    restart: always

  db:
    image: mysql/mysql-server:5.7
    volumes:
      - data-mysql:/var/lib/mysql
      - ./sql/*.sql:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - dbnet
    restart: always
    command: --default-authentication-plugin=mysql_native_password #解决外部无法访问

networks:
  servernet:
  dbnet:

volumes:
  data-storage:
  data-tmp:
  data-mysql:
